vim.g.colors_name = "gruvbox-material"

local palette = {
	bg = "#292828",
	bg1 = "#383432",
	bg2 = "#3c3836",
	bg3 = "#45403d",
	bg4 = "#5a524c",
	fg = "#d4be98",
	fg1 = "#c5b18d",
	fg2 = "#928374",
	fg3 = "#7c6f64",

	red = "#ea6962",
	red_dim = "#b85651",
	green = "#a9b665",
	green_dim = "#8f9a52",
	yellow = "#d8a657",
	yellow_dim = "#c18f41",
	blue = "#7daea3",
	blue_dim = "#68948a",
	magenta = "#d3869b",
	magenta_dim = "#ab6c7d",
	cyan = "#89b482",
	cyan_dim = "#4e664a",
	gray = "#374141",
}

local hl = vim.api.nvim_set_hl

local function set_hl(group, opts)
	hl(0, group, opts)
end

local function link(from, to)
	set_hl(from, { link = to })
end

-- Editor
set_hl("Normal", { fg = palette.fg, bg = palette.bg })
set_hl("NormalFloat", { fg = palette.fg, bg = palette.bg })
set_hl("NormalNC", { fg = palette.fg, bg = palette.bg })
set_hl("FloatBorder", { fg = palette.bg4, bg = palette.bg })
set_hl("FloatTitle", { fg = palette.cyan, bg = palette.bg })
set_hl("ColorColumn", { bg = palette.bg1 })
set_hl("Conceal", { fg = palette.fg3 })
set_hl("Cursor", { fg = palette.bg, bg = palette.blue })
set_hl("lCursor", { fg = palette.bg, bg = palette.blue })
set_hl("CursorIM", { fg = palette.bg, bg = palette.blue })
set_hl("CursorColumn", { bg = palette.bg1 })
set_hl("CursorLine", { bg = palette.bg1 })
set_hl("CursorLineNr", { fg = palette.fg, bold = true })
set_hl("LineNr", { fg = palette.bg4 })
set_hl("SignColumn", { fg = palette.bg4, bg = palette.bg })
set_hl("FoldColumn", { fg = palette.bg4, bg = palette.bg })
set_hl("Folded", { fg = palette.fg3, bg = palette.bg1 })
set_hl("MatchParen", { bg = palette.bg3 })
set_hl("NonText", { fg = palette.bg4 })
set_hl("SpecialKey", { fg = palette.fg2 })
set_hl("Pmenu", { fg = palette.fg, bg = palette.bg })
set_hl("PmenuSel", { fg = palette.fg, bg = palette.bg3 })
set_hl("PmenuSbar", { bg = palette.bg1 })
set_hl("PmenuThumb", { bg = palette.bg3 })
set_hl("Question", { fg = palette.green })
set_hl("QuickFixLine", { bg = palette.gray })
set_hl("Search", { fg = palette.bg, bg = palette.gray })
set_hl("IncSearch", { fg = palette.bg, bg = palette.yellow })
set_hl("CurSearch", { link = "IncSearch" })
set_hl("Substitute", { fg = palette.bg, bg = palette.red })
set_hl("SpellBad", { fg = palette.red, undercurl = true })
set_hl("SpellCap", { fg = palette.blue, undercurl = true })
set_hl("SpellLocal", { fg = palette.cyan, undercurl = true })
set_hl("SpellRare", { fg = palette.magenta, undercurl = true })
set_hl("StatusLine", { fg = palette.fg, bg = palette.bg1 })
set_hl("StatusLineNC", { fg = palette.fg3, bg = palette.bg })
set_hl("TabLine", { fg = palette.fg3, bg = palette.bg })
set_hl("TabLineFill", { bg = palette.bg })
set_hl("TabLineSel", { fg = palette.fg, bg = palette.bg1 })
set_hl("Visual", { bg = palette.gray })
set_hl("VisualNOS", { bg = palette.gray, underline = true })
set_hl("WildMenu", { fg = palette.fg, bg = palette.bg3 })
set_hl("WinSeparator", { fg = palette.bg3 })
set_hl("WinBar", { fg = palette.fg1, bg = palette.bg })
set_hl("WinBarNC", { fg = palette.fg3, bg = palette.bg })

-- Diff
set_hl("DiffAdd", { bg = palette.green_dim })
set_hl("DiffChange", { bg = palette.yellow_dim })
set_hl("DiffDelete", { fg = palette.red, bg = palette.red_dim })
set_hl("DiffText", { bg = palette.blue_dim })

-- Git
set_hl("DiffAdded", { fg = palette.green })
set_hl("DiffRemoved", { fg = palette.red })
set_hl("DiffFile", { fg = palette.fg })
set_hl("DiffNewFile", { fg = palette.green, bold = true })
set_hl("DiffLine", { fg = palette.fg3 })

-- Spelling
set_hl("DiagnosticError", { fg = palette.red })
set_hl("DiagnosticWarn", { fg = palette.yellow })
set_hl("DiagnosticInfo", { fg = palette.blue })
set_hl("DiagnosticHint", { fg = palette.blue })
set_hl("DiagnosticOk", { fg = palette.green })
set_hl("DiagnosticUnderlineError", { undercurl = true, sp = palette.red })
set_hl("DiagnosticUnderlineWarn", { undercurl = true, sp = palette.yellow })
set_hl("DiagnosticUnderlineInfo", { undercurl = true, sp = palette.blue })
set_hl("DiagnosticUnderlineHint", { undercurl = true, sp = palette.blue })
set_hl("DiagnosticSignError", { fg = palette.red })
set_hl("DiagnosticSignWarn", { fg = palette.yellow })
set_hl("DiagnosticSignInfo", { fg = palette.blue })
set_hl("DiagnosticSignHint", { fg = palette.blue })
set_hl("DiagnosticVirtualTextError", { fg = palette.red })
set_hl("DiagnosticVirtualTextWarn", { fg = palette.yellow })
set_hl("DiagnosticVirtualTextInfo", { fg = palette.blue })
set_hl("DiagnosticVirtualTextHint", { fg = palette.blue })
set_hl("DiagnosticFloatingError", { fg = palette.red })
set_hl("DiagnosticFloatingWarn", { fg = palette.yellow })
set_hl("DiagnosticFloatingInfo", { fg = palette.blue })
set_hl("DiagnosticFloatingHint", { fg = palette.blue })

-- Syntax groups
set_hl("Comment", { fg = palette.fg3, italic = true })
set_hl("Constant", { fg = palette.magenta })
set_hl("String", { fg = palette.green })
set_hl("Character", { fg = palette.green })
set_hl("Number", { fg = palette.magenta })
set_hl("Boolean", { fg = palette.magenta_dim })
set_hl("Float", { fg = palette.magenta })
set_hl("Identifier", { fg = palette.fg })
set_hl("Function", { fg = palette.cyan })
set_hl("Statement", { fg = palette.blue, italic = true })
set_hl("Conditional", { fg = palette.blue, italic = true })
set_hl("Repeat", { fg = palette.blue, italic = true })
set_hl("Label", { fg = palette.blue })
set_hl("Operator", { fg = palette.cyan })
set_hl("Keyword", { fg = palette.blue, italic = true })
set_hl("Exception", { fg = palette.blue, italic = true })
set_hl("PreProc", { fg = palette.fg })
set_hl("Include", { fg = palette.fg })
set_hl("Define", { fg = palette.fg })
set_hl("Macro", { fg = palette.fg })
set_hl("PreCondit", { fg = palette.fg })
set_hl("Type", { fg = palette.cyan })
set_hl("StorageClass", { fg = palette.blue })
set_hl("Structure", { fg = palette.cyan })
set_hl("Typedef", { fg = palette.cyan })
set_hl("Special", { fg = palette.magenta_dim })
set_hl("SpecialChar", { fg = palette.magenta_dim })
set_hl("Tag", { fg = palette.blue })
set_hl("Delimiter", { fg = palette.fg1 })
set_hl("SpecialComment", { fg = palette.fg2, bold = true, italic = true })
set_hl("Debug", { fg = palette.red })
set_hl("Underlined", { underline = true })
set_hl("Ignore", { fg = palette.bg4 })
set_hl("Error", { fg = palette.red })
set_hl("Todo", { fg = palette.yellow, bold = true })

-- Treesitter
link("@variable", "Identifier")
link("@variable.builtin", "Special")
link("@variable.parameter", "Identifier")
link("@variable.member", "Identifier")
link("@constant", "Constant")
link("@constant.builtin", "Special")
link("@constant.macro", "Macro")
link("@module", "Include")
link("@module.builtin", "Special")
link("@label", "Label")
link("@string", "String")
link("@string.documentation", "SpecialComment")
link("@string.regexp", "String")
link("@string.escape", "SpecialChar")
link("@string.special", "SpecialChar")
link("@character", "Character")
link("@character.special", "SpecialChar")
link("@number", "Number")
link("@number.float", "Float")
link("@boolean", "Boolean")
link("@type", "Type")
link("@type.builtin", "Type")
link("@type.definition", "Typedef")
link("@attribute", "PreProc")
link("@property", "Identifier")
link("@function", "Function")
link("@function.builtin", "Special")
link("@function.call", "Function")
link("@function.macro", "Macro")
link("@function.method", "Function")
link("@function.method.call", "Function")
link("@constructor", "Type")
link("@operator", "Operator")
link("@keyword", "Keyword")
link("@keyword.conditional", "Conditional")
link("@keyword.repeat", "Repeat")
link("@keyword.return", "Keyword")
link("@keyword.exception", "Exception")
link("@keyword.import", "Include")
link("@keyword.operator", "Operator")
link("@keyword.function", "Keyword")
link("@keyword.modifier", "StorageClass")
link("@keyword.type", "StorageClass")
link("@keyword.coroutine", "Keyword")
link("@keyword.debug", "Debug")
link("@keyword.directive", "PreProc")
link("@keyword.directive.define", "Define")
link("@punctuation.delimiter", "Delimiter")
link("@punctuation.bracket", "Delimiter")
link("@punctuation.special", "Special")
link("@comment", "Comment")
link("@comment.documentation", "SpecialComment")
link("@comment.error", "DiagnosticError")
link("@comment.warning", "DiagnosticWarn")
link("@comment.todo", "Todo")
link("@comment.note", "DiagnosticInfo")
link("@markup.strong", "Bold")
link("@markup.italic", "Italic")
link("@markup.strikethrough", { strikethrough = true })
link("@markup.underline", "Underlined")
link("@markup.heading", "Title")
link("@markup.heading.1", "Title")
link("@markup.heading.2", "Title")
link("@markup.heading.3", "Title")
link("@markup.heading.4", "Title")
link("@markup.heading.5", "Title")
link("@markup.heading.6", "Title")
link("@markup.quote", "Comment")
link("@markup.math", "Special")
link("@markup.link", "Underlined")
link("@markup.link.label", "Special")
link("@markup.link.url", "Underlined")
link("@markup.raw", "String")
link("@markup.list", "Delimiter")
link("@markup.list.checked", "DiagnosticOk")
link("@markup.list.unchecked", "Comment")
link("@diff.plus", "DiffAdded")
link("@diff.minus", "DiffRemoved")
link("@diff.delta", "DiffChange")
link("@tag", "Tag")
link("@tag.attribute", "Attribute")
link("@tag.delimiter", "Delimiter")

-- LSP
set_hl("LspReferenceText", { bg = palette.bg3 })
set_hl("LspReferenceRead", { bg = palette.bg3 })
set_hl("LspReferenceWrite", { bg = palette.fg3 })
set_hl("LspSignatureActiveParameter", { fg = palette.cyan, bold = true })
set_hl("LspCodeLens", { fg = palette.fg3 })
set_hl("LspCodeLensSeparator", { fg = palette.bg4 })

-- Telescope
set_hl("TelescopeNormal", { fg = palette.fg, bg = palette.bg })
set_hl("TelescopeBorder", { fg = palette.bg4, bg = palette.bg })
set_hl("TelescopeSelection", { fg = palette.fg, bg = palette.bg3 })
set_hl("TelescopeSelectionCaret", { fg = palette.cyan, bg = palette.bg3 })
set_hl("TelescopeMultiSelection", { fg = palette.green })
set_hl("TelescopeMatching", { fg = palette.cyan, bold = true })
set_hl("TelescopePromptPrefix", { fg = palette.cyan })
set_hl("TelescopePromptBorder", { fg = palette.bg4, bg = palette.bg })
set_hl("TelescopePromptNormal", { fg = palette.fg, bg = palette.bg })
set_hl("TelescopeResultsBorder", { fg = palette.bg4, bg = palette.bg })
set_hl("TelescopeResultsNormal", { fg = palette.fg, bg = palette.bg })
set_hl("TelescopePreviewBorder", { fg = palette.bg4, bg = palette.bg })
set_hl("TelescopePreviewNormal", { fg = palette.fg, bg = palette.bg })

-- NeoTree
set_hl("NeoTreeNormal", { fg = palette.fg, bg = palette.bg })
set_hl("NeoTreeNormalNC", { fg = palette.fg, bg = palette.bg })
set_hl("NeoTreeDimText", { fg = palette.fg3 })
set_hl("NeoTreeDirectoryName", { fg = palette.fg3 })
set_hl("NeoTreeDirectoryIcon", { fg = palette.fg3 })
set_hl("NeoTreeRootName", { fg = palette.fg, bold = true })
set_hl("NeoTreeFileName", { fg = palette.fg })
set_hl("NeoTreeFileIcon", { fg = palette.fg })
set_hl("NeoTreeFileNameOpened", { fg = palette.fg })
set_hl("NeoTreeFloatBorder", { fg = palette.bg4 })
set_hl("NeoTreeFloatTitle", { fg = palette.cyan })
set_hl("NeoTreeTitleBarBg", { bg = palette.bg1 })
set_hl("NeoTreeGitAdded", { fg = palette.green })
set_hl("NeoTreeGitConflict", { fg = palette.green })
set_hl("NeoTreeGitDeleted", { fg = palette.red })
set_hl("NeoTreeGitModified", { fg = palette.yellow })
set_hl("NeoTreeGitRenamed", { fg = palette.blue })
set_hl("NeoTreeGitUntracked", { fg = palette.fg3 })

-- NvimTree
set_hl("NvimTreeNormal", { fg = palette.fg, bg = palette.bg })
set_hl("NvimTreeNormalNC", { fg = palette.fg, bg = palette.bg })
set_hl("NvimTreeIndentMarker", { fg = palette.bg4 })
set_hl("NvimTreeRootFolder", { fg = palette.fg, bold = true })
set_hl("NvimTreeFolderName", { fg = palette.fg })
set_hl("NvimTreeFolderIcon", { fg = palette.fg3 })
set_hl("NvimTreeOpenedFolderName", { fg = palette.fg })
set_hl("NvimTreeEmptyFolderName", { fg = palette.fg3 })
set_hl("NvimTreeFileName", { fg = palette.fg })
set_hl("NvimTreeFileIcon", { fg = palette.fg })
set_hl("NvimTreeOpenedFile", { fg = palette.fg })
set_hl("NvimTreeGitNew", { fg = palette.green })
set_hl("NvimTreeGitDirty", { fg = palette.yellow })
set_hl("NvimTreeGitDeleted", { fg = palette.red })
set_hl("NvimTreeSpecial", { fg = palette.magenta })
set_hl("NvimTreeSymlink", { fg = palette.cyan })
set_hl("NvimTreeWindowPicker", { fg = palette.fg, bg = palette.bg3 })

-- GitSigns
set_hl("GitSignsAdd", { fg = palette.green })
set_hl("GitSignsChange", { fg = palette.yellow })
set_hl("GitSignsDelete", { fg = palette.red })
set_hl("GitSignsChangedelete", { fg = palette.red })
set_hl("GitSignsTopdelete", { fg = palette.red })
set_hl("GitSignsUntracked", { fg = palette.fg3 })
set_hl("GitSignsAddNr", { fg = palette.green })
set_hl("GitSignsChangeNr", { fg = palette.yellow })
set_hl("GitSignsDeleteNr", { fg = palette.red })
set_hl("GitSignsAddLn", { bg = palette.green_dim })
set_hl("GitSignsChangeLn", { bg = palette.yellow_dim })
set_hl("GitSignsDeleteLn", { bg = palette.red_dim })

-- IndentBlankline
set_hl("IblIndent", { fg = palette.bg3 })
set_hl("IblScope", { fg = palette.bg4 })
set_hl("IndentBlanklineChar", { fg = palette.bg3 })
set_hl("IndentBlanklineContextChar", { fg = palette.bg4 })

-- WhichKey
set_hl("WhichKey", { fg = palette.cyan })
set_hl("WhichKeyGroup", { fg = palette.fg })
set_hl("WhichKeyDesc", { fg = palette.fg })
set_hl("WhichKeySeparator", { fg = palette.bg4 })
set_hl("WhichKeyFloat", { bg = palette.bg })
set_hl("WhichKeyBorder", { fg = palette.bg4 })

-- Mini.nvim
set_hl("MiniCursorword", { bg = palette.bg3 })
set_hl("MiniCursorwordCurrent", { bg = palette.bg3 })
set_hl("MiniIndentscopeSymbol", { fg = palette.bg4 })
set_hl("MiniIndentscopePrefix", { nocombine = true })
set_hl("MiniJump", { bg = palette.cyan, fg = palette.bg })
set_hl("MiniJump2dSpot", { fg = palette.cyan, bold = true, nocombine = true })
set_hl("MiniStarterCurrent", {})
set_hl("MiniStarterHeader", { fg = palette.fg3 })
set_hl("MiniStarterFooter", { fg = palette.fg3, italic = true })
set_hl("MiniStarterItem", { fg = palette.fg })
set_hl("MiniStarterItemBullet", { fg = palette.bg4 })
set_hl("MiniStarterItemPrefix", { fg = palette.yellow })
set_hl("MiniStarterSection", { fg = palette.cyan })
set_hl("MiniStarterQuery", { fg = palette.cyan })
set_hl("MiniStatuslineDevinfo", { fg = palette.fg1 })
set_hl("MiniStatuslineFileinfo", { fg = palette.fg1 })
set_hl("MiniStatuslineFilename", { fg = palette.fg })
set_hl("MiniStatuslineInactive", { fg = palette.fg3 })
set_hl("MiniStatuslineModeNormal", { fg = palette.bg, bg = palette.cyan, bold = true })
set_hl("MiniStatuslineModeInsert", { fg = palette.bg, bg = palette.green, bold = true })
set_hl("MiniStatuslineModeVisual", { fg = palette.bg, bg = palette.magenta, bold = true })
set_hl("MiniStatuslineModeReplace", { fg = palette.bg, bg = palette.red, bold = true })
set_hl("MiniStatuslineModeCommand", { fg = palette.bg, bg = palette.yellow, bold = true })
set_hl("MiniSurround", { bg = palette.yellow, fg = palette.bg })
set_hl("MiniTablineCurrent", { fg = palette.fg, bg = palette.bg1 })
set_hl("MiniTablineFill", { bg = palette.bg })
set_hl("MiniTablineHidden", { fg = palette.fg3, bg = palette.bg })
set_hl("MiniTablineModifiedCurrent", { fg = palette.yellow, bg = palette.bg1 })
set_hl("MiniTablineModifiedHidden", { fg = palette.yellow, bg = palette.bg })
set_hl("MiniTablineModifiedVisible", { fg = palette.yellow, bg = palette.bg1 })
set_hl("MiniTablineTabpagesection", { bg = palette.bg3 })
set_hl("MiniTablineVisible", { fg = palette.fg, bg = palette.bg1 })

-- Dashboard
set_hl("DashboardHeader", { fg = palette.fg3 })
set_hl("DashboardCenter", { fg = palette.fg })
set_hl("DashboardFooter", { fg = palette.fg3, italic = true })
set_hl("DashboardShortcut", { fg = palette.cyan })
set_hl("DashboardKey", { fg = palette.yellow })
set_hl("DashboardDesc", { fg = palette.fg })
set_hl("DashboardIcon", { fg = palette.cyan })

-- Noice
set_hl("NoiceCmdlinePopup", { bg = palette.bg })
set_hl("NoiceCmdlinePopupBorder", { fg = palette.bg4 })
set_hl("NoiceCmdlinePopupBorderSearch", { fg = palette.yellow })
set_hl("NoiceCmdlineIcon", { fg = palette.cyan })
set_hl("NoiceConfirm", { bg = palette.bg })
set_hl("NoiceConfirmBorder", { fg = palette.bg4 })
set_hl("NoiceLspProgressTitle", { fg = palette.fg })
set_hl("NoiceLspProgressClient", { fg = palette.cyan })
set_hl("NoiceLspProgressSpinner", { fg = palette.cyan })

-- Notify
set_hl("NotifyERRORBorder", { fg = palette.red })
set_hl("NotifyERRORIcon", { fg = palette.red })
set_hl("NotifyERRORTitle", { fg = palette.red })
set_hl("NotifyWARNBorder", { fg = palette.yellow })
set_hl("NotifyWARNIcon", { fg = palette.yellow })
set_hl("NotifyWARNTitle", { fg = palette.yellow })
set_hl("NotifyINFOBorder", { fg = palette.blue })
set_hl("NotifyINFOIcon", { fg = palette.blue })
set_hl("NotifyINFOTitle", { fg = palette.blue })
set_hl("NotifyDEBUGBorder", { fg = palette.fg3 })
set_hl("NotifyDEBUGIcon", { fg = palette.fg3 })
set_hl("NotifyDEBUGTitle", { fg = palette.fg3 })
set_hl("NotifyTRACEBorder", { fg = palette.magenta })
set_hl("NotifyTRACEIcon", { fg = palette.magenta })
set_hl("NotifyTRACETitle", { fg = palette.magenta })

-- Leap
set_hl("LeapMatch", { fg = palette.bg, bg = palette.cyan, bold = true })
set_hl("LeapLight", { fg = palette.bg, bg = palette.cyan })
set_hl("LeapLabelPrimary", { fg = palette.bg, bg = palette.cyan, bold = true })
set_hl("LeapLabelSecondary", { fg = palette.bg, bg = palette.green })
set_hl("LeapBackdrop", { fg = palette.bg4 })

-- Hop
set_hl("HopKey", { fg = palette.cyan, bold = true })
set_hl("HopUnmatched", { fg = palette.bg4 })
set_hl("HopPreview", { fg = palette.yellow })
set_hl("HopCursor", { fg = palette.magenta })
set_hl("HopShotCurrent", { bg = palette.bg3 })
set_hl("HopShot1", { bg = palette.bg3 })
set_hl("HopShot2", { bg = palette.bg3 })

-- Cmp
set_hl("CmpDocumentation", { fg = palette.fg, bg = palette.bg })
set_hl("CmpDocumentationBorder", { fg = palette.bg4, bg = palette.bg })
set_hl("CmpCompletion", { fg = palette.fg, bg = palette.bg })
set_hl("CmpCompletionBorder", { fg = palette.bg4, bg = palette.bg })
set_hl("CmpItemAbbr", { fg = palette.fg })
set_hl("CmpItemAbbrDeprecated", { fg = palette.fg3, strikethrough = true })
set_hl("CmpItemAbbrMatch", { fg = palette.cyan })
set_hl("CmpItemAbbrMatchFuzzy", { fg = palette.cyan })
set_hl("CmpItemKind", { fg = palette.fg1 })
set_hl("CmpItemKindText", { fg = palette.fg })
set_hl("CmpItemKindMethod", { fg = palette.cyan })
set_hl("CmpItemKindFunction", { fg = palette.cyan })
set_hl("CmpItemKindConstructor", { fg = palette.cyan })
set_hl("CmpItemKindField", { fg = palette.fg })
set_hl("CmpItemKindVariable", { fg = palette.fg })
set_hl("CmpItemKindClass", { fg = palette.cyan })
set_hl("CmpItemKindInterface", { fg = palette.cyan })
set_hl("CmpItemKindModule", { fg = palette.fg })
set_hl("CmpItemKindProperty", { fg = palette.fg })
set_hl("CmpItemKindUnit", { fg = palette.magenta })
set_hl("CmpItemKindValue", { fg = palette.magenta })
set_hl("CmpItemKindEnum", { fg = palette.red })
set_hl("CmpItemKindKeyword", { fg = palette.blue })
set_hl("CmpItemKindSnippet", { fg = palette.magenta })
set_hl("CmpItemKindColor", { fg = palette.magenta })
set_hl("CmpItemKindFile", { fg = palette.fg })
set_hl("CmpItemKindReference", { fg = palette.fg })
set_hl("CmpItemKindFolder", { fg = palette.fg })
set_hl("CmpItemKindEnumMember", { fg = palette.red })
set_hl("CmpItemKindConstant", { fg = palette.magenta })
set_hl("CmpItemKindStruct", { fg = palette.cyan })
set_hl("CmpItemKindEvent", { fg = palette.cyan })
set_hl("CmpItemKindOperator", { fg = palette.cyan })
set_hl("CmpItemKindTypeParameter", { fg = palette.cyan })
set_hl("CmpItemKindCopilot", { fg = palette.cyan })
set_hl("CmpItemMenu", { fg = palette.fg3 })

-- Fidget
set_hl("FidgetTitle", { fg = palette.cyan })
set_hl("FidgetTask", { fg = palette.fg3 })

-- Highlight URL
set_hl("HighlightURL", { underline = true })

-- Semantic highlights
set_hl("@lsp.type.class", { fg = palette.cyan })
set_hl("@lsp.type.comment", {})
set_hl("@lsp.type.decorator", { fg = palette.cyan })
set_hl("@lsp.type.enum", { fg = palette.cyan })
set_hl("@lsp.type.enumMember", { fg = palette.red })
set_hl("@lsp.type.event", { fg = palette.cyan })
set_hl("@lsp.type.function", { fg = palette.cyan })
set_hl("@lsp.type.interface", { fg = palette.cyan })
set_hl("@lsp.type.keyword", { fg = palette.blue })
set_hl("@lsp.type.macro", { fg = palette.fg })
set_hl("@lsp.type.method", { fg = palette.cyan })
set_hl("@lsp.type.modifier", { fg = palette.blue })
set_hl("@lsp.type.namespace", { fg = palette.fg })
set_hl("@lsp.type.number", { fg = palette.magenta })
set_hl("@lsp.type.operator", { fg = palette.cyan })
set_hl("@lsp.type.parameter", { fg = palette.fg })
set_hl("@lsp.type.property", { fg = palette.fg })
set_hl("@lsp.type.regexp", { fg = palette.magenta_dim })
set_hl("@lsp.type.string", { fg = palette.green })
set_hl("@lsp.type.struct", { fg = palette.cyan })
set_hl("@lsp.type.type", { fg = palette.cyan })
set_hl("@lsp.type.typeParameter", { fg = palette.cyan })
set_hl("@lsp.type.variable", { fg = palette.fg })

-- Terminal colors
vim.g.terminal_color_0 = palette.bg
vim.g.terminal_color_1 = "#ea6962"
vim.g.terminal_color_2 = palette.green
vim.g.terminal_color_3 = "#d8a657"
vim.g.terminal_color_4 = palette.blue
vim.g.terminal_color_5 = "#d3869b"
vim.g.terminal_color_6 = palette.cyan
vim.g.terminal_color_7 = palette.fg
vim.g.terminal_color_8 = palette.bg4
vim.g.terminal_color_9 = "#ea6962"
vim.g.terminal_color_10 = palette.green
vim.g.terminal_color_11 = "#d8a657"
vim.g.terminal_color_12 = palette.blue
vim.g.terminal_color_13 = "#d3869b"
vim.g.terminal_color_14 = palette.cyan
vim.g.terminal_color_15 = palette.fg
